'use client';

import Link from 'next/link';
import { useEffect, useState } from 'react';
import { ArrowRight, ArrowUpRight, Check, ChevronDown, GitBranch, Layers3, Moon, ShieldCheck, Sun, Wallet } from 'lucide-react';

type Theme = 'dark' | 'light';

const networks = ['Ethereum', 'Arbitrum', 'Base', 'BNB Chain', 'OP Mainnet', 'Polygon', 'Avalanche', 'Gnosis', 'Scroll', 'Linea', 'Solana', 'Unichain', 'Sonic', 'zkSync', 'Mantle', 'Blast', 'Berachain'];

function Brand() {
  return <Link className="brand" href="/" aria-label="ArreyX home"><span className="brand-mark"><svg viewBox="0 0 40 40" aria-hidden="true"><path d="M2 33 18 5h8L10 33zm20 0 6-11 11 11zM27 5h12L28 17z" fill="currentColor" /></svg></span>Arrey<span className="brand-x">X</span></Link>;
}

export function HomePage() {
  const [theme, setTheme] = useState<Theme>('dark');
  useEffect(() => { const frame = requestAnimationFrame(() => { const saved = localStorage.getItem('arreyx-theme'); setTheme(saved === 'light' || saved === 'dark' ? saved : window.matchMedia('(prefers-color-scheme: light)').matches ? 'light' : 'dark'); }); return () => cancelAnimationFrame(frame); }, []);
  useEffect(() => { document.documentElement.dataset.theme = theme; document.documentElement.style.colorScheme = theme; }, [theme]);
  function toggleTheme() { const next = theme === 'dark' ? 'light' : 'dark'; localStorage.setItem('arreyx-theme', next); setTheme(next); }

  return <div className="app-shell home-shell">
    <header className="header home-header"><Brand /><nav aria-label="Home navigation"><a href="#features">Product</a><a href="#how-it-works">How it works</a><a href="#faq">FAQ</a></nav><div className="header-actions"><button className="theme-toggle" aria-label={`Switch to ${theme === 'dark' ? 'light' : 'dark'} mode`} onClick={toggleTheme}>{theme === 'dark' ? <Sun size={18} /> : <Moon size={18} />}</button><Link className="home-header-cta" href="/swap">Open app <ArrowUpRight size={16} /></Link></div></header>
    <main className="home-main">
      <section className="home-hero" aria-labelledby="home-title"><div className="hero-copy"><div className="home-eyebrow"><span className="home-status-dot" /> SIMPLE, LIVE, SELF-CUSTODIAL</div><h1 id="home-title">Move assets.<br /><span>Keep control.</span></h1><p>Swap, bridge, and explore live pools across supported networks from one focused interface.</p><div className="hero-actions"><Link className="home-primary" href="/swap">Open ArreyX <ArrowRight size={18} /></Link><a className="home-secondary" href="#how-it-works">How it works <ArrowRight size={17} /></a></div><div className="hero-trust"><span><Check size={15} /> Live routes</span><span><Check size={15} /> No custody</span><span><Check size={15} /> 17 networks</span></div></div><div className="hero-visual" aria-label="Swap and bridge overview"><div className="visual-top"><span>ARREYX / ROUTE</span><span className="visual-live"><span /> LIVE</span></div><div className="visual-path"><div className="visual-node"><span className="visual-node-icon">E</span><div><small>FROM</small><strong>Ethereum</strong></div></div><div className="visual-connection"><span /><span className="visual-connection-icon"><GitBranch size={17} /></span><span /></div><div className="visual-node"><span className="visual-node-icon visual-node-accent">A</span><div><small>TO</small><strong>Arbitrum</strong></div></div></div><div className="visual-lines"><div><span>01</span><strong>Compare routes</strong></div><div><span>02</span><strong>Review output and fees</strong></div><div><span>03</span><strong>Confirm in your wallet</strong></div></div></div></section>
      <section id="features" className="home-section" aria-labelledby="features-title"><div className="section-heading"><span className="section-index">01 / PRODUCT</span><h2 id="features-title">Three tools. One clear interface.</h2><p>Real provider data, simple navigation, and no invented quotes.</p></div><div className="feature-grid"><article className="feature-card"><div className="feature-icon"><ArrowRight size={22} /></div><span className="feature-number">01</span><h3>Swap</h3><p>Compare available output, fees, and route details before you sign.</p><Link href="/swap">Open swap <ArrowUpRight size={16} /></Link></article><article className="feature-card"><div className="feature-icon"><GitBranch size={22} /></div><span className="feature-number">02</span><h3>Bridge</h3><p>Move supported assets across networks and follow transaction progress.</p><Link href="/bridge">Open bridge <ArrowUpRight size={16} /></Link></article><article className="feature-card"><div className="feature-icon"><Layers3 size={22} /></div><span className="feature-number">03</span><h3>Pools</h3><p>Inspect live liquidity, volume, token prices, and pool activity inside ArreyX.</p><Link href="/pools">Explore pools <ArrowUpRight size={16} /></Link></article></div></section>
      <section id="how-it-works" className="home-section how-section" aria-labelledby="how-title"><div className="section-heading"><span className="section-index">02 / HOW IT WORKS</span><h2 id="how-title">From quote to wallet in three steps.</h2><p>You review every detail before anything is signed.</p></div><div className="steps-grid"><div><span className="step-icon"><Wallet size={22} /></span><span className="step-number">01</span><h3>Connect</h3><p>Use a compatible EVM or Solana wallet. Your funds remain in your wallet.</p></div><div><span className="step-icon"><GitBranch size={22} /></span><span className="step-number">02</span><h3>Compare</h3><p>Select assets and review available output, fees, and route details.</p></div><div><span className="step-icon"><ShieldCheck size={22} /></span><span className="step-number">03</span><h3>Confirm</h3><p>Approve the chosen transaction in your wallet and track its progress.</p></div></div></section>
      <section id="networks" className="home-section network-section" aria-labelledby="networks-title"><div className="section-heading compact-heading"><span className="section-index">03 / COVERAGE</span><h2 id="networks-title">Built for the networks you use.</h2><p>Sixteen EVM networks plus Solana. Available assets and routes come from LI.FI’s current catalog.</p></div><div className="network-grid">{networks.map(network => <div className="network-chip" key={network}><span className="network-chip-mark">{network.slice(0, 1)}</span><span>{network}</span></div>)}</div></section>
      <section id="faq" className="home-section faq-section" aria-labelledby="faq-title"><div className="section-heading"><span className="section-index">04 / FAQ</span><h2 id="faq-title">Good questions, clear answers.</h2><p>The essentials before you connect a wallet.</p></div><div className="faq-list"><details><summary><span>Does ArreyX hold my funds?</span><ChevronDown size={18} /></summary><p>No. ArreyX is self-custodial: transactions are prepared in the app and require confirmation in your connected wallet.</p></details><details><summary><span>Are quotes and pool values live?</span><ChevronDown size={18} /></summary><p>Routes and quotes come from LI.FI. Pool liquidity, volume, prices, and activity come from GeckoTerminal. The interface shows an error when current data cannot be loaded.</p></details><details><summary><span>Which networks are supported?</span><ChevronDown size={18} /></summary><p>ArreyX currently exposes sixteen EVM networks and Solana. A specific token or route may still be unavailable if the provider cannot return a valid path.</p></details><details><summary><span>Why can a route change?</span><ChevronDown size={18} /></summary><p>Prices, liquidity, network fees, and available providers change continuously. Always review the final output and wallet request before signing.</p></details><details><summary><span>Can I inspect pools without leaving ArreyX?</span><ChevronDown size={18} /></summary><p>Yes. Pool rows open an internal detail view with current liquidity, volume, pricing, activity, and a shortcut to swap the pair.</p></details></div></section>
      <section className="home-cta" aria-labelledby="cta-title"><div><span className="section-index">READY WHEN YOU ARE</span><h2 id="cta-title">Find your route.</h2><p>Open ArreyX to compare current routes, inspect fees, and review the result.</p></div><Link className="home-primary" href="/swap">Open app <ArrowRight size={18} /></Link></section>
    </main><footer className="home-footer"><Brand /><span>© {new Date().getFullYear()} ArreyX</span><div><a href="https://docs.li.fi/widget/overview" target="_blank" rel="noopener noreferrer">Routing by LI.FI <ArrowUpRight size={12} /></a><a href="https://www.geckoterminal.com/" target="_blank" rel="noopener noreferrer">Pool data by GeckoTerminal <ArrowUpRight size={12} /></a></div></footer>
  </div>;
}
