'use client';

import Link from 'next/link';
import { useEffect, useState } from 'react';
import { ArrowRight, ArrowUpRight, Check, GitBranch, Layers3, Moon, ShieldCheck, Sun, Wallet } from 'lucide-react';

type Theme = 'dark' | 'light';

const networks = ['Ethereum', 'Arbitrum', 'Base', 'BNB Chain', 'OP Mainnet', 'Polygon', 'Avalanche', 'Gnosis', 'Scroll', 'Linea'];

function Brand() {
  return <Link className="brand" href="/" aria-label="ArreyX home"><span className="brand-mark"><svg viewBox="0 0 40 40" aria-hidden="true"><path d="M2 33 18 5h8L10 33zm20 0 6-11 11 11zM27 5h12L28 17z" fill="currentColor" /></svg></span>Arrey<span className="brand-x">X</span></Link>;
}

export function HomePage() {
  const [theme, setTheme] = useState<Theme>('dark');
  useEffect(() => { const frame = requestAnimationFrame(() => { const saved = localStorage.getItem('arreyx-theme'); setTheme(saved === 'light' || saved === 'dark' ? saved : window.matchMedia('(prefers-color-scheme: light)').matches ? 'light' : 'dark'); }); return () => cancelAnimationFrame(frame); }, []);
  useEffect(() => { document.documentElement.dataset.theme = theme; document.documentElement.style.colorScheme = theme; }, [theme]);
  function toggleTheme() { const next = theme === 'dark' ? 'light' : 'dark'; localStorage.setItem('arreyx-theme', next); setTheme(next); }

  return <div className="app-shell home-shell">
    <header className="header home-header"><Brand /><nav aria-label="Home navigation"><a href="#features">Explore</a><a href="#networks">Networks</a><a href="#how-it-works">How it works</a></nav><div className="header-actions"><button className="theme-toggle" aria-label={`Switch to ${theme === 'dark' ? 'light' : 'dark'} mode`} onClick={toggleTheme}>{theme === 'dark' ? <Sun size={18} /> : <Moon size={18} />}</button><Link className="home-header-cta" href="/app">Open app <ArrowUpRight size={16} /></Link></div></header>
    <main className="home-main">
      <section className="home-hero" aria-labelledby="home-title"><div className="hero-copy"><div className="home-eyebrow"><span className="home-status-dot" /> THE EXCHANGE, MADE CLEAR</div><h1 id="home-title">One place to<br /><span>move across chains.</span></h1><p>Swap tokens, bridge between networks, and explore liquidity pools with live data and a clear view of available routes.</p><div className="hero-actions"><Link className="home-primary" href="/app">Get started <ArrowRight size={18} /></Link><a className="home-secondary" href="#features">Explore ArreyX <ArrowRight size={17} /></a></div><div className="hero-trust"><span><Check size={15} /> Live routes</span><span><Check size={15} /> Connected wallet balances</span><span><Check size={15} /> 10 EVM networks</span></div></div><div className="hero-visual" aria-label="Swap and bridge overview"><div className="visual-top"><span>ARREYX / ROUTE OVERVIEW</span><span className="visual-live"><span /> LIVE DATA</span></div><div className="visual-path"><div className="visual-node"><span className="visual-node-icon">E</span><div><small>START</small><strong>Ethereum</strong></div></div><div className="visual-connection"><span /><span className="visual-connection-icon"><GitBranch size={17} /></span><span /></div><div className="visual-node"><span className="visual-node-icon visual-node-accent">A</span><div><small>DESTINATION</small><strong>Arbitrum</strong></div></div></div><div className="visual-lines"><div><span>01</span><strong>Choose your assets</strong></div><div><span>02</span><strong>Compare available routes</strong></div><div><span>03</span><strong>Review in your wallet</strong></div></div><div className="visual-caption">Quotes and fees appear in the app when a live route is available.</div></div></section>
      <section id="features" className="home-section" aria-labelledby="features-title"><div className="section-heading"><span className="section-index">01 / EXPLORE</span><h2 id="features-title">Everything you need to move.</h2><p>Each view uses current provider data. If a route or pool cannot be loaded, the app shows that clearly.</p></div><div className="feature-grid"><article className="feature-card"><div className="feature-icon"><ArrowRight size={22} /></div><span className="feature-number">01</span><h3>Swap</h3><p>Compare available token exchange routes, including the expected output, fees, and route details before signing.</p><Link href="/app">Open swap <ArrowUpRight size={16} /></Link></article><article className="feature-card"><div className="feature-icon"><GitBranch size={22} /></div><span className="feature-number">02</span><h3>Bridge</h3><p>Move supported assets between networks through live cross-chain routes and track transaction progress.</p><Link href="/app?view=bridge">Open bridge <ArrowUpRight size={16} /></Link></article><article className="feature-card"><div className="feature-icon"><Layers3 size={22} /></div><span className="feature-number">03</span><h3>Pools</h3><p>Discover trending pools with live liquidity and 24-hour volume, then open the pool at its source.</p><Link href="/app?view=pools">Explore pools <ArrowUpRight size={16} /></Link></article></div></section>
      <section id="networks" className="home-section network-section" aria-labelledby="networks-title"><div className="section-heading"><span className="section-index">02 / COVERAGE</span><h2 id="networks-title">Connected where you are.</h2><p>Explore ten EVM networks. Available token pairs and routes are determined by LI.FI’s live catalog.</p></div><div className="network-grid">{networks.map((network, index) => <div className="network-chip" key={network}><span className="network-chip-mark">{network.slice(0, 1)}</span><span>{network}</span><small>{String(index + 1).padStart(2, '0')}</small></div>)}</div></section>
      <section id="how-it-works" className="home-section how-section" aria-labelledby="how-title"><div className="section-heading"><span className="section-index">03 / HOW IT WORKS</span><h2 id="how-title">A clear path from start to finish.</h2><p>You stay in control of every transaction.</p></div><div className="steps-grid"><div><span className="step-icon"><Wallet size={22} /></span><span className="step-number">01</span><h3>Connect a wallet</h3><p>Use a compatible EVM wallet to view actual balances and prepare a transaction.</p></div><div><span className="step-icon"><GitBranch size={22} /></span><span className="step-number">02</span><h3>Find a route</h3><p>Choose your networks, tokens, and amount. Review live output, fees, and route details.</p></div><div><span className="step-icon"><ShieldCheck size={22} /></span><span className="step-number">03</span><h3>Review and sign</h3><p>Confirm the transaction in your wallet. Cross-chain progress is tracked in the app.</p></div></div></section>
      <section className="home-cta" aria-labelledby="cta-title"><div><span className="section-index">READY WHEN YOU ARE</span><h2 id="cta-title">Move with a clearer view.</h2><p>Open the app to see current routes, wallet balances, and available pools.</p></div><Link className="home-primary" href="/app">Open app <ArrowRight size={18} /></Link></section>
    </main><footer className="home-footer"><Brand /><span>© {new Date().getFullYear()} ArreyX</span><div><a href="https://docs.li.fi/widget/overview" target="_blank" rel="noopener noreferrer">Routing by LI.FI <ArrowUpRight size={12} /></a><a href="https://www.geckoterminal.com/" target="_blank" rel="noopener noreferrer">Pool data by GeckoTerminal <ArrowUpRight size={12} /></a></div></footer>
  </div>;
}
